---
name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      # checkout and env setup
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build the nix shell
        run: nix develop --command just --version
      - name: Install Rust toolchain with rustup
        run: nix develop --command cargo --version
      - uses: Swatinem/rust-cache@v2

      # setup databases
      - name: Start databases
        run: nix develop --command just dbs/start
      - name: Seed databases
        run: nix develop --command just dbs/seed

      # run tests
      - name: Run tests
        run: nix develop --command just test
